"""Configuraciones globales del proyecto."""
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
DATA_RAW_DIR = BASE_DIR / "data" / "raw"
DATA_CLEAN_DIR = BASE_DIR / "data" / "clean"
REPORTS_DIR = BASE_DIR / "reports"

EXCEL_FILE = "SALDO - FLUJO DE PAGOS 2026.xlsx"
EXCEL_SHEET = "DATA ORIGINAL"
SKIP_ROWS = 2

MONEDAS_VALIDAS = ["SOLES", "DOLARES"]
BANCOS_VALIDOS = ["BBVA", "BCP", "BLACK"]
CONDICION_DEUDA_VALIDA = "PENDIENTE DE PAGO"

ACEPTANTES_VALIDOS = ["BLACK", "COLCHONES VIVE", "DREAM TEAM", "GRUPO ISD"]

PRODUCTOS_VALIDOS = [
    "DEUDA BANCOS", "EFACT", "GRAPAS", "IMPUESTOS", 
    "IRIS SOLEDAD", "MANGAS", "NOTEX", "PABILO", "PASTAS", "PLANILLA"
]

GIRADORES_VALIDOS = [
    "ALQUILERES IMPUESTOS", "EFACT SAC", "GUANGZHOU HONGDI NEW MATERIAL CO. LTD",
    "IMPORTADORA MASTER SAC / VEDONA", "IMPUESTOS PLANILLA", 
    "IRIS SOLEDAD DE LA CRUZ / TERRENO - CASA", "LAUREANO ROQUE SAC",
    "MALBEZ S.R.LTDA", "ONYX INTERNATIONAL SAC / S&M", 
    "PLANILLA - HABERES", "PRESTAMO BCP / 90K + 13.509 INTERES",
    "SERVICIOS GRAFICOS FA EIRL",
    "ONYX INTERNATIONAL SAC / S&M ",
    "SIN GIRADOR"  # Valor para registros sin girador
]

PATRONES_FACTURA = ["CUOTA", "FACT", "LT", "ETA"]
